# Generated by Django 4.0.3 on 2022-03-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='taximg/')),
                ('legend', models.CharField(default=None, max_length=125, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('publication_year', models.CharField(max_length=50)),
                ('icn_identifier', models.IntegerField()),
                ('trophic_mode', models.CharField(choices=[('lich', 'Lichen'), ('lich_fun', 'Champignon lichénicole')], default='Lichen', max_length=25)),
                ('cover_image', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ivlichen.image')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(to='ivlichen.image')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivlichen.taxon')),
            ],
        ),
    ]
