# Generated by Django 4.0.3 on 2022-03-06 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ivlichen', '0002_observation_date_observation_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
