# Generated by Django 4.0.3 on 2022-03-16 19:08

from django.db import migrations, models
import marklichen.models


class Migration(migrations.Migration):

    dependencies = [
        ('ivlichen', '0003_alter_observation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='fine_substrate',
            field=marklichen.models.MarkdownField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='identifier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='substrate',
            field=models.CharField(choices=[('epi', 'épiphyte'), ('sax', 'saxicole'), ('cort', 'corticole'), ('terr', 'terricole'), ('musc', 'muscicole'), ('lich', 'lichénicole')], default='epi', max_length=5),
        ),
        migrations.AddField(
            model_name='taxon',
            name='remarks',
            field=marklichen.models.MarkdownField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='shape',
            field=models.CharField(choices=[('crust', 'crustacé'), ('lepr', 'lépreux'), ('comp', 'composé'), ('fol', 'foliacé'), ('frut', 'fruticuleux'), ('squa', 'squamuleux'), ('gel', 'gélatineux'), ('other', 'autre')], default='crust', max_length=25),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='trophic_mode',
            field=models.CharField(choices=[('lich', 'lichen'), ('lich_fun', 'champignon lichénicole')], default='lich', max_length=25),
        ),
    ]
