# Generated by Django 4.0.3 on 2022-03-16 19:38

from django.db import migrations, models
import django.db.models.deletion
import marklichen.models


class Migration(migrations.Migration):

    dependencies = [
        ('ivlichen', '0004_observation_fine_substrate_observation_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='division',
            field=models.CharField(choices=[('asco', 'Ascomycota'), ('basidio', 'Basidiomycota')], default='asco', max_length=10),
        ),
        migrations.AddField(
            model_name='taxon',
            name='family',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='fine_substrate',
            field=marklichen.models.MarkdownField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='locality',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='cover_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ivlichen.image'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='remarks',
            field=marklichen.models.MarkdownField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
