# Generated by Django 4.0.3 on 2022-03-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivlichen', '0005_taxon_division_taxon_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='identifier',
        ),
        migrations.AddField(
            model_name='observation',
            name='outside_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='observation',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=125, null=True),
        ),
    ]
