# Generated by Django 4.0.3 on 2022-03-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivlichen', '0006_remove_observation_identifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='outside_inventory',
            new_name='outside_scope',
        ),
    ]
