# Generated by Django 4.0.3 on 2022-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivlichen', '0008_remove_observation_fine_substrate_observation_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='legend',
        ),
        migrations.AddField(
            model_name='taxon',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
