# Generated by Django 4.0.3 on 2022-03-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivlichen', '0009_remove_image_legend_taxon_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
    ]
